In [1]:
#### Problem 1

If we list all the natural numbers below 10 that are multiples of 3 or 5, we get 3, 5, 6 and 9. The sum of these multiples is 23.

Find the sum of all the multiples of 3 or 5 below 1000.

LoadError: LoadError: syntax: extra token "we" after end of expression
while loading In[1], in expression starting on line 3

In [2]:
# sum of multiples of n below N.
function sum_of_multiples(n, N)
    count = floor((N - 1)/n)
    return Int(count * n * (1 + count)/2)
end

function pe1(N)
    sum_of_multiples(3, N) + sum_of_multiples(5, N) - sum_of_multiples(15, N)
end
pe1(1000)

233168

----
#### Problem 2

Each new term in the Fibonacci sequence is generated by adding the previous two terms. By starting with 1 and 2, the first 10 terms will be:

1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...

By considering the terms in the Fibonacci sequence whose values do not exceed four million, find the sum of the even-valued terms.

----
Remark:

_even terms occurs at k = 3m + 1 position, satisfying linear recurrence_ $a_{k+1} = a_{k-1} + 4\,a_k $

_sum of even terms will satisfy same linear recurrence with a constant_ $S_{k+1} = S_{k-1} + 4\,S_{k - 2}$

In [3]:
function index_of_fib(N)
    div(log(√5 * N), log((1 + √5)/2))
end

function pe2(N)
    index_of_even = div(index_of_fib(N), 3)
    κ = 0.5 * (3/2/√5 + 0.5)
    α = 2 + √5   
    Int(round(κ * α^index_of_even - 0.5))
end
pe2(4_000_000)

4613732

----
#### Problem 3

The prime factors of 13195 are 5, 7, 13 and 29.

What is the largest prime factor of the number 600851475143 ?

In [4]:
function pe3(N)
    maximum(factor(N).keys)
end
pe3(600851475143)

140614868358160

----
#### Problem 4

A palindromic number reads the same both ways. The largest palindrome made from the product of two 2-digit numbers is 9009 = 91 × 99.

Find the largest palindrome made from the product of two 3-digit numbers.

In [5]:
function ispalindrome(n)
    m = n
    r = 0
    d = 0
    while(m > 0)
        d = m %  10
        r = r * 10 + d
        m = div(m, 10)
    end
    if (r == n)
        return true 
    end
    return false;
end

function pe4()
    r = 0
    max = 0
    for p = 999:-1:100
        for q = 990:-11:100
            r = p * q
            if (ispalindrome(r)) 
                if (r > max) 
                    max = r 
                end
            end
        end
    end
    max
end
pe4()

906609

----
#### Problem 5

2520 is the smallest number that can be divided by each of the numbers from 1 to 10 without any remainder.

What is the smallest positive number that is evenly divisible by all of the numbers from 1 to 20?

In [6]:
function pe5(n)
    m = 1
    for i = 2:n
        m = lcm(m, i)
    end
    m
end
pe5(20)

232792560

----
#### Problem 6



The sum of the squares of the first ten natural numbers is,
$$1^2 + 2^2 + ... + 10^2 = 385$$

The square of the sum of the first ten natural numbers is,
$$(1 + 2 + ... + 10)^2 = 55^2 = 3025$$

Hence the difference between the sum of the squares of the first ten natural numbers and the square of the sum is $3025 − 385 = 2640$.

Find the difference between the sum of the squares of the first one hundred natural numbers and the square of the sum.

In [7]:
function pe6(n) 
    Int(((n * (n + 1))/2)^2 - n * (n + 1)*(2*n + 1)/6)
end

pe6(100)

25164150

----
#### Problem 7


By listing the first six prime numbers: 2, 3, 5, 7, 11, and 13, we can see that the 6th prime is 13.

What is the 10,001st prime number?

Remark: From [Rosser's theorem](https://en.wikipedia.org/wiki/Rosser's_theorem), for $n > 6$,

$\log n + \log\log n - 1 < \dfrac{p_n}{n} < \log n + \log\log n $

In [8]:
function pe7(n)  
    upper = 10001 * (log(10001) + log(log(10001)))
    primes(Int(round(upper)))[10001]
end

pe7(10_001)

104743

----
#### Problem 8

The four adjacent digits in the 1000-digit number that have the greatest product are 9 × 9 × 8 × 9 = 5832.

_for data: see in code_

Find the thirteen adjacent digits in the 1000-digit number that have the greatest product. What is the value of this product?

In [9]:
function pe8()
    str = """
    73167176531330624919225119674426574742355349194934
    96983520312774506326239578318016984801869478851843
    85861560789112949495459501737958331952853208805511
    12540698747158523863050715693290963295227443043557
    66896648950445244523161731856403098711121722383113
    62229893423380308135336276614282806444486645238749
    30358907296290491560440772390713810515859307960866
    70172427121883998797908792274921901699720888093776
    65727333001053367881220235421809751254540594752243
    52584907711670556013604839586446706324415722155397
    53697817977846174064955149290862569321978468622482
    83972241375657056057490261407972968652414535100474
    82166370484403199890008895243450658541227588666881
    16427171479924442928230863465674813919123162824586
    17866458359124566529476545682848912883142607690042
    24219022671055626321111109370544217506941658960408
    07198403850962455444362981230987879927244284909188
    84580156166097919133875499200524063689912560717606
    05886116467109405077541002256983155200055935729725
    71636269561882670428252483600823257530420752963450"""
    str = replace(str, "\n","")
    
    max = BigInt(0)
    for i = 1:length(str) - 12
        n = BigInt(1)
        for j = 0:12
            n *= (str[i + j] - '0')
            if (n == 0) 
                break
            end
        end
        if (n > max) 
            max = n
        end
    end
    max
end
pe8()

23514624000

#### Problem 9

A Pythagorean triplet is a set of three natural numbers, $a < b < c$, for which,

$$a^2 + b^2 = c^2$$

For example, 32 + 42 = 9 + 16 = 25 = 52.

There exists exactly one Pythagorean triplet for which $a + b + c = 1000$.
Find the product $abc$.

In [10]:
# a < b < c
# a + b > c ==> c < (a + b + c) / 2 = 500
# 2c^2 >= (a + b)^2 ==> c >= 500/(1 + sqrt(2) 
# b > a ==> c - 1 > b > (1000 - c)/2

function pe9()
    for c = Int(round(500/(1+√2))):499
        for b = div(1000 - c, 2) : c - 1
            a = 1000 - b - c
            if (a^2 + b^2 == c^2) 
                return  a * b * c
            end
        end
    end
end
pe9()

31875000

#### Problem 10

The sum of the primes below 10 is 2 + 3 + 5 + 7 = 17.

Find the sum of all the primes below two million.

In [11]:
# DP
function pe10(n)
    r = Int(round(√n))
    temp = Array{Int, 1}(2 * r - 1)
    for i = 1 : r
        temp[i] = div(n, i)
    end
    
    for i = r + 1 : 2 * r - 1
        temp[i] = 2 * r - i
    end
    
    S = Dict{Int, Int}()
    for i in temp
        S[i] = Int(i * (i + 1)/2 - 1)
    end
    
    for p = 2 : r 
        if haskey(S, p) && S[p] > S[p - 1]
            sp = S[p - 1]
            p2 = p * p
            for v in temp
                if v < p2
                    break
                end
                S[v] -= p * (S[div(v, p)] - sp)
            end
        end
    end
    S[n]
end

pe10(2000_000)

142913828922

#### Problem 11

In the 20×20 grid below, four numbers along a diagonal line have been marked in red.

_for data: see in code_

The product of these numbers is 26 × 63 × 78 × 14 = 1788696.

What is the greatest product of four adjacent numbers in the same direction (up, down, left, right, or diagonally) in the 20×20 grid?

In [12]:
function pe11()
    A = [
        08 02 22 97 38 15 00 40 00 75 04 05 07 78 52 12 50 77 91 08
        49 49 99 40 17 81 18 57 60 87 17 40 98 43 69 48 04 56 62 00
        81 49 31 73 55 79 14 29 93 71 40 67 53 88 30 03 49 13 36 65
        52 70 95 23 04 60 11 42 69 24 68 56 01 32 56 71 37 02 36 91
        22 31 16 71 51 67 63 89 41 92 36 54 22 40 40 28 66 33 13 80
        24 47 32 60 99 03 45 02 44 75 33 53 78 36 84 20 35 17 12 50
        32 98 81 28 64 23 67 10 26 38 40 67 59 54 70 66 18 38 64 70
        67 26 20 68 02 62 12 20 95 63 94 39 63 08 40 91 66 49 94 21
        24 55 58 05 66 73 99 26 97 17 78 78 96 83 14 88 34 89 63 72
        21 36 23 09 75 00 76 44 20 45 35 14 00 61 33 97 34 31 33 95
        78 17 53 28 22 75 31 67 15 94 03 80 04 62 16 14 09 53 56 92
        16 39 05 42 96 35 31 47 55 58 88 24 00 17 54 24 36 29 85 57
        86 56 00 48 35 71 89 07 05 44 44 37 44 60 21 58 51 54 17 58
        19 80 81 68 05 94 47 69 28 73 92 13 86 52 17 77 04 89 55 40
        04 52 08 83 97 35 99 16 07 97 57 32 16 26 26 79 33 27 98 66
        88 36 68 87 57 62 20 72 03 46 33 67 46 55 12 32 63 93 53 69
        04 42 16 73 38 25 39 11 24 94 72 18 08 46 29 32 40 62 76 36
        20 69 36 41 72 30 23 88 34 62 99 69 82 67 59 85 74 04 36 16
        20 73 35 29 78 31 90 01 74 31 49 71 48 86 81 16 23 57 05 54
        01 70 54 71 83 51 54 69 16 92 33 48 61 43 52 01 89 19 67 48]  
    
    ret = 0
    V = H = L = R = 0
    for i = 1:20
        for j = 1:20
            if (i <= 17) 
                V = A[i, j] * A[i + 1, j] * A[i + 2, j] * A[i + 3, j]
            end
            
            if (j <= 17)
                H = A[i, j] * A[i, j + 1] * A[i, j + 2] * A[i, j + 3]
            end
            
            if (i <= 17 && j <= 17)
                L = A[i, j] * A[i + 1, j + 1] * A[i + 2, j + 2] * A[i + 3, j + 3]
                R = A[i + 3, 18 - j] * A[i + 2, 19 - j] * A[i + 1, 20 - j] * A[i, 21 - j]
            end
            ret = maximum([ret, V, H, L, R])
        end
    end
    ret
end

pe11()

70600674

#### Problem 12

The sequence of triangle numbers is generated by adding the natural numbers. So the 7th triangle number would be 1 + 2 + 3 + 4 + 5 + 6 + 7 = 28. The first ten terms would be:

1, 3, 6, 10, 15, 21, 28, 36, 45, 55, ...

Let us list the factors of the first seven triangle numbers:
```
     1: 1
     3: 1,3
     6: 1,2,3,6
    10: 1,2,5,10
    15: 1,3,5,15
    21: 1,3,7,21
    28: 1,2,4,7,14,28
```
We can see that 28 is the first triangle number to have over five divisors.

What is the value of the first triangle number to have over five hundred divisors?

In [13]:
function num_of_factor(m)
    count = 2
    for k = 2: m - 1
        if (m % k == 0) 
            count += 1
        end
    end
    count
end

function pe12(n)
    count = 0
    i = 0
    while(count < n)
        i = i + 1
        if (i % 2 == 1)
            count = num_of_factor(i) * num_of_factor(div((i + 1),2))
        else
            count = num_of_factor(div(i, 2)) * num_of_factor(i + 1)
        end
    end
    Int((i) * (i + 1)/2)
end

pe12(500)

76576500

#### Problem 13

Work out the first ten digits of the sum of the following one-hundred 50-digit numbers.

_for data: see in code_

In [14]:
function pe13()
    sum([
        37107287533902102798797998220837590246510135740250
        46376937677490009712648124896970078050417018260538
        74324986199524741059474233309513058123726617309629
        91942213363574161572522430563301811072406154908250
        23067588207539346171171980310421047513778063246676
        89261670696623633820136378418383684178734361726757
        28112879812849979408065481931592621691275889832738
        44274228917432520321923589422876796487670272189318
        47451445736001306439091167216856844588711603153276
        70386486105843025439939619828917593665686757934951
        62176457141856560629502157223196586755079324193331
        64906352462741904929101432445813822663347944758178
        92575867718337217661963751590579239728245598838407
        58203565325359399008402633568948830189458628227828
        80181199384826282014278194139940567587151170094390
        35398664372827112653829987240784473053190104293586
        86515506006295864861532075273371959191420517255829
        71693888707715466499115593487603532921714970056938
        54370070576826684624621495650076471787294438377604
        53282654108756828443191190634694037855217779295145
        36123272525000296071075082563815656710885258350721
        45876576172410976447339110607218265236877223636045
        17423706905851860660448207621209813287860733969412
        81142660418086830619328460811191061556940512689692
        51934325451728388641918047049293215058642563049483
        62467221648435076201727918039944693004732956340691
        15732444386908125794514089057706229429197107928209
        55037687525678773091862540744969844508330393682126
        18336384825330154686196124348767681297534375946515
        80386287592878490201521685554828717201219257766954
        78182833757993103614740356856449095527097864797581
        16726320100436897842553539920931837441497806860984
        48403098129077791799088218795327364475675590848030
        87086987551392711854517078544161852424320693150332
        59959406895756536782107074926966537676326235447210
        69793950679652694742597709739166693763042633987085
        41052684708299085211399427365734116182760315001271
        65378607361501080857009149939512557028198746004375
        35829035317434717326932123578154982629742552737307
        94953759765105305946966067683156574377167401875275
        88902802571733229619176668713819931811048770190271
        25267680276078003013678680992525463401061632866526
        36270218540497705585629946580636237993140746255962
        24074486908231174977792365466257246923322810917141
        91430288197103288597806669760892938638285025333403
        34413065578016127815921815005561868836468420090470
        23053081172816430487623791969842487255036638784583
        11487696932154902810424020138335124462181441773470
        63783299490636259666498587618221225225512486764533
        67720186971698544312419572409913959008952310058822
        95548255300263520781532296796249481641953868218774
        76085327132285723110424803456124867697064507995236
        37774242535411291684276865538926205024910326572967
        23701913275725675285653248258265463092207058596522
        29798860272258331913126375147341994889534765745501
        18495701454879288984856827726077713721403798879715
        38298203783031473527721580348144513491373226651381
        34829543829199918180278916522431027392251122869539
        40957953066405232632538044100059654939159879593635
        29746152185502371307642255121183693803580388584903
        41698116222072977186158236678424689157993532961922
        62467957194401269043877107275048102390895523597457
        23189706772547915061505504953922979530901129967519
        86188088225875314529584099251203829009407770775672
        11306739708304724483816533873502340845647058077308
        82959174767140363198008187129011875491310547126581
        97623331044818386269515456334926366572897563400500
        42846280183517070527831839425882145521227251250327
        55121603546981200581762165212827652751691296897789
        32238195734329339946437501907836945765883352399886
        75506164965184775180738168837861091527357929701337
        62177842752192623401942399639168044983993173312731
        32924185707147349566916674687634660915035914677504
        99518671430235219628894890102423325116913619626622
        73267460800591547471830798392868535206946944540724
        76841822524674417161514036427982273348055556214818
        97142617910342598647204516893989422179826088076852
        87783646182799346313767754307809363333018982642090
        10848802521674670883215120185883543223812876952786
        71329612474782464538636993009049310363619763878039
        62184073572399794223406235393808339651327408011116
        66627891981488087797941876876144230030984490851411
        60661826293682836764744779239180335110989069790714
        85786944089552990653640447425576083659976645795096
        66024396409905389607120198219976047599490197230297
        64913982680032973156037120041377903785566085089252
        16730939319872750275468906903707539413042652315011
        94809377245048795150954100921645863754710598436791
        78639167021187492431995700641917969777599028300699
        15368713711936614952811305876380278410754449733078
        40789923115535562561142322423255033685442488917353
        44889911501440648020369068063960672322193204149535
        41503128880339536053299340368006977710650566631954
        81234880673210146739058568557934581403627822703280
        82616570773948327592232845941706525094512325230608
        22918802058777319719839450180888072429661980811197
        77158542502016545090413245809786882778948721859617
        72107838435069186155435662884062257473692284509516
        20849603980134001723930671666823555245252804609722
        53503534226472524250874054075591789781264330331690])
end
pe13()

5537376230390876637302048746832985971773659831892672

#### Problem 14

The following iterative sequence is defined for the set of positive integers:

n → n/2 (n is even)

n → 3n + 1 (n is odd)

Using the rule above and starting with 13, we generate the following sequence:
13 → 40 → 20 → 10 → 5 → 16 → 8 → 4 → 2 → 1

It can be seen that this sequence (starting at 13 and finishing at 1) contains 10 terms. Although it has not been proved yet (Collatz Problem), it is thought that all starting numbers finish at 1.

Which starting number, under one million, produces the longest chain?

NOTE: Once the chain starts the terms are allowed to go above one million.

In [15]:
# DP
function pe14(n)
    collatz = Dict{Int, Int}(1 => 1)
    
    function iter(m)
        if !haskey(collatz, m)
            if (m % 2 ==0)
                collatz[m] = iter(m / 2) + 1
            else
                collatz[m] = iter(3 * m + 1)+ 1
            end
        end
        return collatz[m]
    end
    
    for i = 1:n
        iter(i)
    end
    
    maximum([(collatz[i], i) for i = 1:n])[2]
end

pe14(1000_000)

837799

#### Problem 15

Starting in the top left corner of a 2×2 grid, and only being able to move to the right and down, there are exactly 6 routes to the bottom right corner.

<img src="pics/p015.gif">


How many such routes are there through a 20×20 grid?

In [16]:
function pe15(n)
    BigInt(factorial(2 *BigInt(n)) /factorial(BigInt(n))^2)
end

pe15(20)

137846528820

#### Problem 16

$2^{15}= 32768$ and the sum of its digits is 3 + 2 + 7 + 6 + 8 = 26.

What is the sum of the digits of the number $2^{1000}$?

In [17]:
function pe16(n)
    sum(digits(BigInt(2)^n, 10))
end

pe16(1000)

1366

----
#### Problem 17

If the numbers 1 to 5 are written out in words: one, two, three, four, five, then there are 3 + 3 + 5 + 4 + 4 = 19 letters used in total.

If all the numbers from 1 to 1000 (one thousand) inclusive were written out in words, how many letters would be used?

NOTE: Do not count spaces or hyphens. For example, 342 (three hundred and forty-two) contains 23 letters and 115 (one hundred and fifteen) contains 20 letters. The use of "and" when writing out numbers is in compliance with British usage.

In [18]:
function pe17()
    digit = [3, 3, 5, 4, 4, 3, 5, 5, 4]
    teens = [3, 6, 6, 8, 8, 7, 7, 9, 8, 8]
    tens  =  [6, 6, 5, 5, 5, 7, 6, 6]
    hundred = 7
    hundred_and = 10
    
    below_hundred =  sum(digit) + sum(teens) + 10 * sum(tens) + 8 * sum(digit)
    below_thousand = 100 * sum(digit) + hundred * 9 + hundred_and * 9 * 99 + 9 * below_hundred 
    one_thousand = 11
    
    return below_hundred + below_thousand + one_thousand
    
end

pe17()

21124

----
#### Problem 18

By starting at the top of the triangle below and moving to adjacent numbers on the row below, the maximum total from top to bottom is 23.

```
   3
  7 4
 2 4 6
8 5 9 3
```

That is, 3 + 7 + 4 + 9 = 23.

Find the maximum total from top to bottom of the triangle below:

_for data: see in code_

NOTE: As there are only 16384 routes, it is possible to solve this problem by trying every route. However, Problem 67, is the same challenge with a triangle containing one-hundred rows; it cannot be solved by brute force, and requires a clever method! ;o)

In [19]:
# DP
function pe18()
    triangle = Any[[75],
                [95, 64],
                [17, 47, 82],
                [18, 35, 87, 10],
                [20,  4, 82, 47, 65],
                [19,  1, 23, 75,  3, 34],
                [88,  2, 77, 73,  7, 63, 67],
                [99, 65,  4, 28,  6, 16, 70, 92],
                [41, 41, 26, 56, 83, 40, 80, 70, 33],
                [41, 48, 72, 33, 47, 32, 37, 16, 94, 29],
                [53, 71, 44, 65, 25, 43, 91, 52, 97, 51, 14],
                [70, 11, 33, 28, 77, 73, 17, 78, 39, 68, 17, 57],
                [91, 71, 52, 38, 17, 14, 91, 43, 58, 50, 27, 29, 48],
                [63, 66,  4, 68, 89, 53, 67, 30, 73, 16, 69, 87, 40, 31],
                [ 4, 62, 98, 27, 23,  9, 70, 98, 73, 93, 38, 53, 60,  4, 23]]
    for row = length(triangle) :-1: 2
        for  i = 1 : length(triangle[row]) - 1
            triangle[row - 1][i] += max(triangle[row][i], triangle[row][i + 1])
        end
    end   
    triangle[1][1]
end

pe18()

1074

#### Problem 19

You are given the following information, but you may prefer to do some research for yourself.

    1 Jan 1900 was a Monday.
    Thirty days has September,
    April, June and November.
    All the rest have thirty-one,
    Saving February alone,
    Which has twenty-eight, rain or shine.
    And on leap years, twenty-nine.
    A leap year occurs on any year evenly divisible by 4, but not on a century unless it is divisible by 400.

How many Sundays fell on the first of the month during the twentieth century (1 Jan 1901 to 31 Dec 2000)?

In [20]:
#  brute force
function pe19()
    dt = Dates.Date(1901, 1,1) : Dates.Month(1): Dates.Date(2000, 12, 1)
    count = 0
    for d in dt
        if Dates.dayofweek(d) == 7
            count += 1
        end
    end
    count
end
pe19()

171

#### Problem 20

n! means n × (n − 1) × ... × 3 × 2 × 1

For example, 10! = 10 × 9 × ... × 3 × 2 × 1 = 3628800,

and the sum of the digits in the number 10! is 3 + 6 + 2 + 8 + 8 + 0 + 0 = 27.

Find the sum of the digits in the number 100!

In [21]:
function pe20()
    sum(digits(factorial(BigInt(100)), 10))
end
pe20()

648

#### Problem 21



Let d(n) be defined as the sum of proper divisors of n (numbers less than n which divide evenly into n).
If d(a) = b and d(b) = a, where a ≠ b, then a and b are an amicable pair and each of a and b are called amicable numbers.

For example, the proper divisors of 220 are 1, 2, 4, 5, 10, 11, 20, 22, 44, 55 and 110; therefore d(220) = 284. The proper divisors of 284 are 1, 2, 4, 71 and 142; so d(284) = 220.

Evaluate the sum of all the amicable numbers under 10000.

In [22]:
function sum_of_proper_divisor(n)
    factors = factor(n)
    sum = 1
    for key in factors
        sum *= div(key.first^(key.second + 1) - 1, key.first - 1)
    end
    sum -= n
end

function pe21()
    sum = 0
    for i = 2 : 10000
        α = sum_of_proper_divisor(i)
        if (α!= i && sum_of_proper_divisor(α) == i) 
            sum += i 
        end
    end
    sum
end
pe21()

31626

#### Problem 22

Using [names.txt](data/p022_names.txt) (right click and 'Save Link/Target As...'), a 46K text file containing over five-thousand first names, begin by sorting it into alphabetical order. Then working out the alphabetical value for each name, multiply this value by its alphabetical position in the list to obtain a name score.

For example, when the list is sorted into alphabetical order, COLIN, which is worth 3 + 15 + 12 + 9 + 14 = 53, is the 938th name in the list. So, COLIN would obtain a score of 938 × 53 = 49714.

What is the total of all the name scores in the file?

In [23]:
function score(s)
    r = 0
    for t in s
        r += t - 'A' + 1
    end
    r
end

function pe22()
    str = split(readlines(open("./data/p022_names.txt"))[1][2:end- 1],"\",\"")
    sort!(str)
    s = 0
    index = 1
    for name in str
        s += index * score(name)
        index += 1
    end
    s
end

pe22()

871198282

----
#### Problem 23

A perfect number is a number for which the sum of its proper divisors is exactly equal to the number. For example, the sum of the proper divisors of 28 would be 1 + 2 + 4 + 7 + 14 = 28, which means that 28 is a perfect number.

A number n is called deficient if the sum of its proper divisors is less than n and it is called abundant if this sum exceeds n.

As 12 is the smallest abundant number, 1 + 2 + 3 + 4 + 6 = 16, the smallest number that can be written as the sum of two abundant numbers is 24. By mathematical analysis, it can be shown that all integers greater than 28123 can be written as the sum of two abundant numbers. However, this upper limit cannot be reduced any further by analysis even though it is known that the greatest number that cannot be expressed as the sum of two abundant numbers is less than this limit.

Find the sum of all the positive integers which cannot be written as the sum of two abundant numbers.

In [24]:
# DP
function is_redundant_sum(n, is_redundant)
    for i = 12 : div(n, 2)
        d1 = d2 = false
        if (haskey(is_redundant, i)) 
            d1 = is_redundant[i]
        else
            d1 = sum_of_proper_divisor(i) > i
            is_redundant[i] = d1
        end
        
        if (haskey(is_redundant, n - i)) 
            d2 = is_redundant[n - i]
        else
            d2 = sum_of_proper_divisor(n - i) > (n - i)
            is_redundant[n - i] = d2
        end
        if (d1 && d2) 
            return true
        end
    end
    return false
end

function pe23()
    is_redundant = Dict{Int, Bool}()
    s = 0
    for i = 1 : 28123
        if (!is_redundant_sum(i, is_redundant)) 
            s += i
        end
    end
    s
end
pe23()

4179871

#### Problem 24

A permutation is an ordered arrangement of objects. For example, 3124 is one possible permutation of the digits 1, 2, 3 and 4. If all of the permutations are listed numerically or alphabetically, we call it lexicographic order. The lexicographic permutations of 0, 1 and 2 are:
```
012   021   102   120   201   210
```
What is the millionth lexicographic permutation of the digits 0, 1, 2, 3, 4, 5, 6, 7, 8 and 9?

In [25]:
function pe24(n)
    parse(Int, join(nthperm(Array(0:9), n)))
end

pe24(1000_000)

2783915460

#### Problem 25

The Fibonacci sequence is defined by the recurrence relation:

    Fn = Fn−1 + Fn−2, where F1 = 1 and F2 = 1.

Hence the first 12 terms will be:

    F1 = 1
    F2 = 1
    F3 = 2
    F4 = 3
    F5 = 5
    F6 = 8
    F7 = 13
    F8 = 21
    F9 = 34
    F10 = 55
    F11 = 89
    F12 = 144

The 12th term, F12, is the first term to contain three digits.

What is the index of the first term in the Fibonacci sequence to contain 1000 digits?

In [26]:
function pe25(n)
    Int(ceil(((n - 1) * log(10) + log(√5))/log((1 + √5)/2)))
end

pe25(1000)

4782

#### Problem 26

A unit fraction contains 1 in the numerator. The decimal representation of the unit fractions with denominators 2 to 10 are given:

    1/2	= 	0.5
    1/3	= 	0.(3)
    1/4	= 	0.25
    1/5	= 	0.2
    1/6	= 	0.1(6)
    1/7	= 	0.(142857)
    1/8	= 	0.125
    1/9	= 	0.(1)
    1/10	= 	0.1 

Where 0.1(6) means 0.166666..., and has a 1-digit recurring cycle. It can be seen that 1/7 has a 6-digit recurring cycle.

Find the value of d < 1000 for which 1/d contains the longest recurring cycle in its decimal fraction part.

In [27]:
function pe26()
    num = primes(1000)
    max = 0
    max_i = -1
    for i in num
        while(i % 2 == 0) 
            i /= 2
        end
        while(i % 5 == 0)
            i /= 5
        end
        r = 10
        n = 1
        if (i > 1)
            while(r % i != 1)
                r *= 10
                r %= i
                n += 1
            end
            if (n > max) 
                max_i = i
                max = n
            end
        end
    end
    max_i
end
pe26()

983

#### Problem 27

Euler discovered the remarkable quadratic formula:

n² + n + 41

It turns out that the formula will produce 40 primes for the consecutive values n = 0 to 39. However, when n = 40, 402 + 40 + 41 = 40(40 + 1) + 41 is divisible by 41, and certainly when n = 41, 41² + 41 + 41 is clearly divisible by 41.

The incredible formula  n² − 79n + 1601 was discovered, which produces 80 primes for the consecutive values n = 0 to 79. The product of the coefficients, −79 and 1601, is −126479.

Considering quadratics of the form:

    n² + an + b, where |a| < 1000 and |b| < 1000

    where |n| is the modulus/absolute value of n
    e.g. |11| = 11 and |−4| = 4

Find the product of the coefficients, a and b, for the quadratic expression that produces the maximum number of primes for consecutive values of n, starting with n = 0.

In [28]:
# a + b > 0
# b is prime
function pe27()
    primelist = primes(1000)
    max = res = curr = 0    
    for b in primelist
        for a = -b + 1:999
            for n = 0 : b - 1
                curr = n * n + n * a + b
                if (isprime(curr) && curr > 0)
                    continue
                else
                    if (max < n)
                        max = n
                        res = a * b
                    end
                    break;
                end
            end
        end
    end
    res
end
pe27()

-59231

#### Problem 28

Starting with the number 1 and moving to the right in a clockwise direction a 5 by 5 spiral is formed as follows:

```
21 22 23 24 25
20  7  8  9 10
19  6  1  2 11
18  5  4  3 12
17 16 15 14 13
```
It can be verified that the sum of the numbers on the diagonals is 101.

What is the sum of the numbers on the diagonals in a 1001 by 1001 spiral formed in the same way?

In [29]:
# if we think it as recurrence. S(1) = 1, S(3) = 25, S(5) = 101, S(7) = 261 and S(n) is a cubic polynomial of n.
# A = zeros(4,4)
# coef = [1, 3, 5, 7]
# b = [1, 25, 101, 261]
# y = [1, 1001, 1001^2, 1001^3]
# for i = 1:4
#     for j = 1:4
#         A[i, j] = coef[i]^(j-1)
#     end
# end
# x = A\b
# round(Int, y' * x)

# normal approach as follows.
function pe28(n)
    ret = 1
    for i = 1:div(n,2)
        ret += 4 * (2*i + 1)^2 - 12*i
    end
    ret
end
pe28(1001)

669171001

#### Problem 29

Consider all integer combinations of $a^b$ for 2 ≤ a ≤ 5 and 2 ≤ b ≤ 5:

$$2^2=4, 2^3=8, 2^4=16, 2^5=32$$
$$3^2=9, 3^3=27, 3^4=81, 3^5=243$$
$$4^2=16, 4^3=64, 4^4=256, 4^5=1024$$
$$5^2=25, 5^3=125, 5^4=625, 5^5=3125$$

If they are then placed in numerical order, with any repeats removed, we get the following sequence of 15 distinct terms:

4, 8, 9, 16, 25, 27, 32, 64, 81, 125, 243, 256, 625, 1024, 3125

How many distinct terms are in the sequence generated by ab for 2 ≤ a ≤ 100 and 2 ≤ b ≤ 100?

In [30]:
function pe29()
    s= Set{BigInt}()
    for a = 2 : 100
        for b = 2 : 100
            push!(s, BigInt(a)^BigInt(b))
        end
    end
    length(s)
end
pe29()

9183

#### Problem 30

Surprisingly there are only three numbers that can be written as the sum of fourth powers of their digits:

$$1634 = 1^4 + 6^4 + 3^4 + 4^4$$
$$8208 = 8^4 + 2^4 + 0^4 + 8^4$$
$$9474 = 9^4 + 4^4 + 7^4 + 4^4$$

As $1 = 1^4$ is not a sum it is not included.

The sum of these numbers is 1634 + 8208 + 9474 = 19316.

Find the sum of all the numbers that can be written as the sum of fifth powers of their digits.

In [31]:
# should be no more than 6 digits
function pe30()
    ret = 0
    for i = 2:6 * 9^5
        if  sum(digits(i).^5) == i
            ret += i
        end
    end
    ret
end    
pe30()

443839

#### Problem 31

In England the currency is made up of pound, £, and pence, p, and there are eight coins in general circulation:

    1p, 2p, 5p, 10p, 20p, 50p, £1 (100p) and £2 (200p).

It is possible to make £2 in the following way:

    1×£1 + 1×50p + 2×20p + 1×5p + 1×2p + 3×1p

How many different ways can £2 be made using any number of coins?

In [32]:
# product of polynomials, truncated as s terms
function conv(a, b, s)
    n = length(a)
    m = length(b)
    c = zeros(s)
    for j = 0 : n - 1
        for k = 0 : m - 1
            if (j + k + 1 <= s)
                c[j + k + 1] += a[j + 1] * b[k + 1]
            end
        end
    end
    return c
end
    
function pe31()
    coin = [1, 2, 5, 10, 20, 50, 100, 200]
    ret = zeros(201)
    ret[1] = 1
    for i in coin
        poly = zeros(201)
        for j = 0 : div(200, i)
            poly[round(Int,i * j) + 1] = 1
        end
        ret = conv(ret, poly, 201)
    end
    round(Int, ret[201])
end

pe31()

73682

#### Problem 32

We shall say that an n-digit number is pandigital if it makes use of all the digits 1 to n exactly once; for example, the 5-digit number, 15234, is 1 through 5 pandigital.

The product 7254 is unusual, as the identity, 39 × 186 = 7254, containing multiplicand, multiplier, and product is 1 through 9 pandigital.

Find the sum of all products whose multiplicand/multiplier/product identity can be written as a 1 through 9 pandigital.
HINT: Some products can be obtained in more than one way so be sure to only include it once in your sum.

In [33]:
function combination(l, k, current, list)
    if k == length(current)
        push!(list, current)
    else
        j = (length(current) > 0) ? (last(current)+1) : 1
        for i=j:l
            combination(l, k, [current;i], list)
        end
    end
end

function pe32()
    s = Set{Int}()
    list = []
    combination(9, 5,[], list)
    for l in list
        for i in permutations(l)
            p = (10 * i[1] + i[2]) * (100 * i[3] + 10 * i[4] + i[5])
            q = i[1] * (1000 * i[2] + 100 * i[3] + 10 * i[4] + i[5])

            if sum(union(Set(digits(p)), Set((i)))) == 45 && p < 10000
                push!(s, p)
            end

            if sum(union(Set(digits(q)), Set((i)))) == 45 && q < 10000
                push!(s, q)
            end
        end
    end
    sum(s)
end
pe32()

45228

#### Problem 33

The fraction 49/98 is a curious fraction, as an inexperienced mathematician in attempting to simplify it may incorrectly believe that 49/98 = 4/8, which is correct, is obtained by cancelling the 9s.

We shall consider fractions like, 30/50 = 3/5, to be trivial examples.

There are exactly four non-trivial examples of this type of fraction, less than one in value, and containing two digits in the numerator and denominator.

If the product of these four fractions is given in its lowest common terms, find the value of the denominator.

In [34]:
function pe33()
    s = 1;
    for i = 11:99
        for j = 11:99
            if i < j
                if (i % 10) == round(Int, floor(j/10)) &&  i // j == round(Int, floor(i/10)) // (j % 10)
                s *= i//j
                end
            end
        end
    end
    den(s)
end
pe33()

100

#### Problem 34

145 is a curious number, as 1! + 4! + 5! = 1 + 24 + 120 = 145.

Find the sum of all numbers which are equal to the sum of the factorial of their digits.

Note: as 1! = 1 and 2! = 2 are not sums they are not included.

In [35]:
function pe34()
    ret = 0
    for i = 3 : 999999
        if sum(map(factorial, digits(i))) == i
            ret += i
        end
    end
    ret
    end
pe34()

40730


#### Problem 35

The number, 197, is called a circular prime because all rotations of the digits: 197, 971, and 719, are themselves prime.

There are thirteen such primes below 100: 2, 3, 5, 7, 11, 13, 17, 31, 37, 71, 73, 79, and 97.

How many circular primes are there below one million?

In [36]:
function is_circular(n)
    m = n
    k = 0
    l = 1
    while(m != 0) 
        m = div(m, 10)
        l *= 10
        k += 1
    end
    l /= 10
    for j = 0: k - 1
        n = div((n - n % 10), 10) + l * (n % 10)
        if (!isprime(round(Int, n))) 
            return false
        end
    end
    return true
end

function pe35()
    n = 0
    for i in primes(1000_000)
        if (is_circular(i))
            n += 1
        end
    end
    n
end
pe35()

55

#### Problem 36

The decimal number, $585 = 1001001001_2$ (binary), is palindromic in both bases.

Find the sum of all numbers, less than one million, which are palindromic in base 10 and base 2.

(Please note that the palindromic number, in either base, may not include leading zeros.)

In [37]:
function is_palindromic(a)
    n = length(a)
    for i = 1 : div(n, 2)
        if a[i] != a[n + 1 - i]
            return false
        end
    end
    return true
end

function pe36()
    ret = 0
    for i = 1:1000_000
        if is_palindromic(digits(i, 10)) && is_palindromic(digits(i, 2))
            ret += i
        end
    end
    ret
end
pe36()

872187

#### Problem 37

The number 3797 has an interesting property. Being prime itself, it is possible to continuously remove digits from left to right, and remain prime at each stage: 3797, 797, 97, and 7. Similarly we can work from right to left: 3797, 379, 37, and 3.

Find the sum of the only eleven primes that are both truncatable from left to right and right to left.

NOTE: 2, 3, 5, and 7 are not considered to be truncatable primes.

In [38]:
function is_truncatable(x)
    y = x
    k = 0
    while(y != 0)
        if !isprime(y) 
            return false
        else
            y = div(y, 10)
            k += 1
        end
    end
    
    while(x != 0)
        if !isprime(x)
            return false
        else
            x = x % (10^k)
            k -= 1
        end
    end
    return true
end

function pe37()
    ret = 0
    count = 0
    primelist = primes(800_000)
    for i in primelist 
        if is_truncatable(i) && i > 10
            ret += i
            count += 1
            # reach the largest one
            if count == 11
                break
            end
        end
    end
    ret
end
pe37()

748317

#### Problem 38

Take the number 192 and multiply it by each of 1, 2, and 3:

    192 × 1 = 192
    192 × 2 = 384
    192 × 3 = 576

By concatenating each product we get the 1 to 9 pandigital, 192384576. We will call 192384576 the concatenated product of 192 and (1,2,3)

The same can be achieved by starting with 9 and multiplying by 1, 2, 3, 4, and 5, giving the pandigital, 918273645, which is the concatenated product of 9 and (1,2,3,4,5).

What is the largest 1 to 9 pandigital 9-digit number that can be formed as the concatenated product of an integer with (1,2, ... , n) where n > 1?

In [39]:
function pe38()
    data = []
    for n = 2:5
        for i = 10^(div(10, n) - 2):10^(div(10, n) - 1)
            m = []
            for j = 1 : n
                m = vcat(m , reverse(digits(j * i)))
            end
            if length(m) == 9 && length(Set(m)) == 9 && sum(m) == 45
                push!(data, join(m))
            end
        end
    end     
    parse(Int,sort!(data, rev= true)[1])
end
pe38()

932718654

#### Problem 39

If p is the perimeter of a right angle triangle with integral length sides, {a,b,c}, there are exactly three solutions for p = 120.

{20,48,52}, {24,45,51}, {30,40,50}

For which value of p ≤ 1000, is the number of solutions maximised?

In [40]:
function pe39()
    max_p = 0
    max = 0
    for p = 3 : 1000
        count = 0
        for c = round(Int, p/(1 + √2)) : div(p, 2)
            for a = div(p - c, 2) : c - 1
                b = p - c - a
                if (a^2 + b^2 == c^2)
                    count += 1
                end
            end
        end
        if count > max
            max = count
            max_p = p
        end
    end
    max_p
end
pe39()

840

#### Problem 40

An irrational decimal fraction is created by concatenating the positive integers:

0.123456789101112131415161718192021...

It can be seen that the 12th digit of the fractional part is 1.

If dn represents the nth digit of the fractional part, find the value of the following expression.

$d_1 × d_{10} × d_{100} × d_{1000} × d_{10000} × d_{100000} × d_{1000000}$

In [41]:
function pe40()
    current = []
    num = 0
    ret = 1
    k = 0
    while(k < 1000_000)
        k += 1
        if isempty(current) 
            num += 1
            current = digits(num)
        end
        
        d = pop!(current)
        
        if (k == 1 || k == 10 || k == 10^2 ||
            k == 10^3 || k == 10^4 || k == 10^5 || k == 10^6)
            ret *= d
        end 
    end
    ret
end
pe40()

210

#### Problem 41

We shall say that an n-digit number is pandigital if it makes use of all the digits 1 to n exactly once. For example, 2143 is a 4-digit pandigital and is also prime.

What is the largest n-digit pandigital prime that exists?

In [42]:
function pe41()
    ret = 0
    x = permutations("1234567")
    for i in x
        t = parse(Int, join(i))
        if isprime(t) && ret < t
            ret = t
        end
    end
    ret
end
pe41()

7652413

#### Problem 42

The nth term of the sequence of triangle numbers is given by, $t_n = \frac{1}{2}n(n+1)$; so the first ten triangle numbers are:

1, 3, 6, 10, 15, 21, 28, 36, 45, 55, ...

By converting each letter in a word to a number corresponding to its alphabetical position and adding these values we form a word value. For example, the word value for SKY is $19 + 11 + 25 = 55 = t_{10}$. If the word value is a triangle number then we shall call the word a triangle word.

Using words.txt (right click and 'Save Link/Target As...'), a 16K text file containing nearly two-thousand common English words, how many are triangle words?

In [43]:
function pe42()
    str = split(readlines(open("./data/p042_words.txt"))[1][2:end- 1],"\",\"")
    count = 0
    for i in str
        t = √(8 * (sum(map(x->(i[x] -'A' + 1), 1:length(i)))) + 1) 
        y = round(Int, t)
        if abs(y - t) < 1e-15
            count += 1
        end
    end
    count
end
pe42()

162

#### Problem 43

The number, 1406357289, is a 0 to 9 pandigital number because it is made up of each of the digits 0 to 9 in some order, but it also has a rather interesting sub-string divisibility property.

Let $d_1$ be the 1st digit, $d_2$ be the 2nd digit, and so on. In this way, we note the following:

$d_2d_3d_4=406$ is divisible by 2

$d_3d_4d_5=063$ is divisible by 3

$d_4d_5d_6=635$ is divisible by 5

$d_5d_6d_7=357$ is divisible by 7

$d_6d_7d_8=572$ is divisible by 11

$d_7d_8d_9=728$ is divisible by 13

$d_8d_9d_{10}=289$ is divisible by 17

Find the sum of all 0 to 9 pandigital numbers with this property.

In [44]:
function pe43()
    str = permutations("0123456789")
    primelist = [2, 3, 5, 7, 11, 13, 17]
    ret = 0
    for i in str
        flag = true
        for k = 2 : 8
            if parse(Int, join(i[k : k+2])) % primelist[k - 1] != 0
                flag = false
                break
            end
        end
        if (flag == true)
            ret += parse(Int, join(i))
        end
    end
    ret
end
pe43()

16695334890

#### Problem 44

Pentagonal numbers are generated by the formula, $P_n=n(3n−1)/2$. The first ten pentagonal numbers are:

1, 5, 12, 22, 35, 51, 70, 92, 117, 145, ...

It can be seen that $P_4 + P_7 = 22 + 70 = 92 = P_8$. However, their difference, 70 − 22 = 48, is not pentagonal.

Find the pair of pentagonal numbers, $P_j$ and $P_k$, for which their sum and difference are pentagonal and $D = |P_k − P_j|$ is minimised; what is the value of $D$?

In [45]:
function is_in(L, x)
    y = searchsorted(L, x)
    return y.start == y.stop
end

function pe44()
    D = Inf
    L = map(x->x*(3*x - 1)/2, 1:2500)
    for i = 1:2500
        for j = i + 1: 2500
            if is_in(L, L[i] + L[j]) && is_in(L, L[j] - L[i]) && D > L[j] - L[i]
                D = L[j] - L[i]
            end
        end
    end
    round(Int,D)
end
pe44()

5482660

#### Problem 45

Triangle, pentagonal, and hexagonal numbers are generated by the following formulae:

Triangle 	  	$T_n=n(n+1)/2\quad$ 	  	1, 3, 6, 10, 15, ...

Pentagonal 	  	$P_n=n(3n−1)/2\quad$ 	  	1, 5, 12, 22, 35, ...

Hexagonal 	  	$H_n=n(2n−1)\quad$ 	  	1, 6, 15, 28, 45, ...

It can be verified that $T_{285} = P_{165} = H_{143} = 40755$.

Find the next triangle number that is also pentagonal and hexagonal.

In [46]:
function pe45()
    n = count = H = 0
    while(true)
        n += 1
        H = n * (2 * n - 1)
        t = √(1 + 8 * H)
        p = √(1 + 24 * H)
        if round(t) == t && round(p) == p && (Int(p) + 1) % 6 == 0
            count += 1
        end
        if count == 3
            break
        end
    end
    H
end
pe45()

1533776805